o=input('enter file name:')
# Key=input("who u r lookin for:")

# r=search(o, Key)
# if (r[0]==True):
#     print("exist")
#     print(f'dans le bloc :{r[1]+1} and position :{r[2]+1}')
# else:
#     print("exist not")
#     print(r[1],r[2])
# insert(o)
# # f=open('testins', 'rb+')
# # buf=lirebloc(f,2)
# # print(buf[0])
# #insert('2obj')
# afficher_fichier()
# deleteLogic(o)
# afficher_fichier()
# deletephisiq(o)
# afficher_fichier()